app/accounts/urls.py
from django.urls import path
# from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

app/rental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('', include('rentalapp.urls')),
    path('', include('accounts.urls')),
]

#Needed in case we're using gunicorn instead of runserver
#It is not reccomended to keep this while on development. Instead use server like nginx
#Informations from https://stackoverflow.com/questions/12800862/how-to-make-django-serve-static-files-with-gunicorn
urlpatterns += staticfiles_urlpatterns()

app/rentalapp/urls.py
from django.urls import path

from . import views

app_name = 'rentalapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('description/', views.description, name='description'),
    path('books/', views.books, name='books'),
    path('books/result/', views.result, name='result'),
    path('books/reserve/<str:book_id>/', views.reserve_book, name='reserve_book'),
    path('books/<str:book_id>/', views.book_details, name='book_details'),
]

app/accounts/models.py
from django.db import models

# Create your models here.

app/rentalapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# # Create your models here.
# class User(models.Model):
#     #We have name, surname and email inside in-built user (in django)
#     # name = models.CharField(max_length=30)
#     # surname = models.CharField(max_length=30)
#     # email = models.CharField(max_length=60)
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     birth_date = models.DateField()
#     address = models.CharField(max_length=100)
#     is_librarian = models.BooleanField(default=False)

#     def __str__(self):
#         return str(self.user.username)

class Author(models.Model):
    name = models.CharField(max_length=30)
    secondname = models.CharField(max_length=30, default='')
    surname = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name} {self.secondname + " " if self.secondname!="" else ""}{self.surname}'


class Book(models.Model):
    title = models.CharField(max_length=30)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    is_avaiable = models.BooleanField(default=True)
    is_reserved = models.BooleanField(default=False)
    
    def __str__(self):
        return f'"{self.title}" by {self.author}'


class Action(models.Model):
    action = models.CharField(max_length=60, default='CUSTOM')

    def __str__(self):
        return self.action

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    date = models.DateTimeField()
    end_date = models.DateField(null = True, blank=True)

    #We can: Reserve, Cancel-Reservation, Rent, Extend, Return
    action_type = models.ForeignKey(Action, on_delete=models.CASCADE)
    custom_action = models.CharField(max_length = 60, blank = True)

    def __str__(self):
        return f'{self.book} - {self.action_type}'

class Category(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return f'{self.name}'

class CategoryFilter(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)

app/accounts/forms.py
#get the form from django-registration
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MyUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = '__all__'
        fields = ['username','first_name','last_name','email']

app/rentalapp/forms.py
from django import forms

class SearchBooksForm(forms.Form):
    given_title = forms.CharField(label='Title of the book', required=False)
    given_title.widget.attrs['placeholder'] = 'Give the title of desired book (could be part of the title)'
    given_title.widget.attrs['name'] = 'given_title'

    given_author_name = forms.CharField(label='Author name', required=False)
    given_author_name.widget.attrs['placeholder'] = 'Give author name)'
    given_author_name.widget.attrs['name'] = 'given_author_name'

    given_author_surname = forms.CharField(label='Author surname', required=False)
    given_author_surname.widget.attrs['placeholder'] = 'Give author surname)'
    given_author_surname.widget.attrs['name'] = 'given_author_surname'
    

app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from .forms import MyUserCreationForm

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() #It saves date inside database (creating new user) and returns created user
            #log the user in
            login(request, user)
            return redirect('/')
    else:
        form = MyUserCreationForm()

    #Returns unvalid form if method=POST or empty one if method=GET  
    stuff_for_frontend = {'form':form}
    return render(request, 'accounts/signup.html', stuff_for_frontend)

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #Log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('/')
    else:
        form = AuthenticationForm()

    #Returns unvalid form if method=POST or empty one if method=GET  
    stuff_for_frontend = {'form':form}
    return render(request, 'accounts/login.html', stuff_for_frontend)
    
def logout_view(request):
    logout(request)
    return redirect('/')

app/rentalapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import Book, Author, Order, Action
from .forms import SearchBooksForm
from django.utils import timezone


def index(request):
    """
    View which displays main page
    """
    context = {}
    return render(request, 'rentalapp/index.html', context)




def description(request):
    """
    View which displays description page
    """
    context = {}
    return render(request, 'rentalapp/description.html', context)

def books(request):
    """
    View which allow to manage books
    """
    if request.method == 'POST':
        form = SearchBooksForm(request.POST)
        if form.is_valid():
            #Get some result
            return HttpResponseRedirect('/book/result/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchBooksForm()

    context = {'form':form}
    return render(request, 'rentalapp/books.html', context)


def result(request):
    """
    View which allow to see result of searching
    """
    if request.method == 'POST':
        form = SearchBooksForm(request.POST)
    else:
        form = SearchBooksForm()

    author_list = Author.objects.filter(
        name__contains=request.POST.get("given_author_name",""), 
        surname__contains=request.POST.get("given_author_surname","")
        )
    book_list = []
    for author in author_list:
        temp = author.book_set.filter(title__contains=request.POST.get("given_title",""))
        if temp.exists():
            book_list.append(temp)

    context = {'book_list':book_list, 'form':form}
    return render(request, 'rentalapp/result.html', context)


def book_details(request, book_id):
    """
    View which displays description page
    """
    book = Book.objects.get(id=book_id)
    orders = Order.objects.filter(book=book).order_by('-date')
    
    context = {'book':book, 'orders':orders}
    return render(request, 'rentalapp/book_details.html', context)

def reserve_book(request, book_id):
    """
    View which displays description page
    """
    if request.method == 'POST':
        b = Book.objects.get(id=book_id)
        b.is_reserved = True
        b.save()
        o = Order(
            user=request.user, 
            book=b, 
            date=timezone.now(), 
            action_type = Action.objects.get(action='RESERVE')
            )
        o.save()
    return redirect('/')

app/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden", name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Log in">
  </form>
{% endblock %}

app/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Log in">
  </form>
{% endblock %}

app/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<style>
.helptext{ display: block; margin-bottom:40px}
</style>
  <h1>Signup</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

app/rentalapp/templates/rentalapp/book_details.html
{% extends 'base.html' %}
{% block content %}
    <h4>Book details view</h4>
    <h6>{{ book }}</h6>
        <ul>
        <li>Is avaiable? : {{ book.is_avaiable }}</li>
        <li>Is reserved? : {{ book.is_reserved }}</li>
        <br>

        {% if not book.is_reserved %}
        <form action="{% url 'rentalapp:reserve_book' book_id=book.id %}", method="post">
                {% csrf_token %}
                <button type="submit">Reserve book</button>
        </form>
        <br>
        {% endif %}

        <br>
        {% if user.is_staff %}
            {% for order in orders %}
                <li style="position: relative">
                        {{ order.date|date:'Y-m-d H:i' }} - 
                        {{ order.action_type }} by {{ order.user.first_name }} {{ order.user.last_name }}
                </li>
            {% endfor %}
        {% endif %}
        </ul>

{% endblock %}

app/rentalapp/templates/rentalapp/books.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h3 style="text-align: center">Search for the book</h3>
        <br />

        <form action="/books/result/" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>

        {% block result %}
        {% endblock %}
    </div>
{% endblock %}

app/rentalapp/templates/rentalapp/description.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h3 style="text-align: center">How it works?</h3>
        <div class="row">
            <a href="http://google.pl">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">find_in_page</i>
                        <p>Search database</p>
                        <p class="light center">User can search database for desired book with userform designed for this.</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">calendar_today</i>
                        <p>Reserve the book</p>
                        <p class="light center">If desired book is aviable user can reserve this book.</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">check_box</i>
                        <p>Rent reserved book</p>
                        <p class="light center">After reservation user have 7 days to take reserved book from our library</p>
                    </div>
                </div>
            </a>
        </div>


    {% block result %}
    {% endblock %}
{% endblock %}

app/rentalapp/templates/rentalapp/index.html
{% extends 'base.html' %}
{% block content %}
        <h3 style="text-align: center">What you want to do?</h3>
        <br />
        <div class="row">
            <a href="books">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">library_books</i>
                        <p>Manage Books/Authors</p>
                        <p class="light center">Add, modify or remove books or autor in the library database.</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">bookmarks</i>
                        <p>Manage categories</p>
                        <p class="light center">Add/remove/modify categories. Add books to categories.</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">account_circle</i>
                        <p>Manage Users</p>
                        <p class="light center">Modify user informations, assign permissions.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="row">
            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">search</i>
                        <p>Search Database</p>
                        <p class="light center">Donec eget magna porta, aliquam diam sed, volutpat metus</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">format_list_bulleted</i>
                        <p>Your reservations/rentals</p>
                        <p class="light center">Donec eget magna porta, aliquam diam sed, volutpat metus.</p>
                    </div>
                </div>
            </a>

            <a href="#">
                <div class="col s4">
                    <div class="center navtile">
                        <i class="large material-icons">tab</i>
                        <p>Explore categories</p>
                        <p class="light center">Donec eget magna porta, aliquam diam sed, volutpat metus</p>
                    </div>
                </div>
            </a>
        </div>


    {% block result %}
    {% endblock %}
{% endblock %}

app/rentalapp/templates/rentalapp/result.html
{% extends 'rentalapp/books.html' %}
{% block result %}
    {% if book_list %}
        {% for books_of_author in book_list %}
            <h5>{{ books_of_author.0.author }}</h5>
            <ul>
            {% for book in books_of_author %}
            <a class="non-colored" href="{% url 'rentalapp:book_details' book_id=book.id %}">
                <li>
                "{{ book.title }}"
                {% if book.is_avaiable %}
                - book is available
                {% elif book.is_reserved %}
                - book is not available and book is book.is_reserved
                {% else %}
                - book is not available but can be book.is_reserved
                {% endif %}
                </li>
            </a>
            {% endfor %}
            </ul>  
        {% endfor %}
    {% else %}
        <p>No books are available.</p>
    {% endif %}

{% endblock result %}

app/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rent a book</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />

</head>

<body>
    <nav class="grey darken-2">
        <div class="container nav-wrapper">
            <a href="/" class="brand-logo">Rentalapp</a>
            <ul id="nav-mobile" class="right">
                {% if user.is_authenticated %}
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'rentalapp:description' %}">Description</a></li>
                {% if user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Admin panel</a></li>
                {% endif %}
                <li><a href="{% url 'accounts:logout' %}">Log out ({{ user.get_username }})</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                {% endif %}

                
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
  


<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body >
</html>